### ISSUE TITLE
Undocumented dependency on "bearssl"

### ISSUE THREAD

**Issue by mouse07410** [riastradh/daence#3]
```
clang -c -o beardaence.o -O3 -std=gnu18 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I/opt/local/include -Werror -MMD -MF beardaence.d  -Itweetnacl -DDAENCE_GENERATE_KAT beardaence.c
beardaence.c:34:10: fatal error: 'bearssl.h' file not found
#include <bearssl.h>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by mouse07410** [comment]
Ping? Anybody still maintains this repo?

**Comment by riastradh** [comment]
Sorry about that.  Somehow I didn't get the notifications about this issue.

FYI, BearSSL is only needed by `make` because it builds and runs _all_ the implementations and their automatic tests in the repository, including beardaence.c which is designed for use in an application that already uses BearSSL.  If you have an application using libsodium, all you need is chachadaence.c and chachadaence.h -- there's no need to use BearSSL too in that application.
